import { BoardRowType, Card, CardType, Faction, SpecialAbility } from "./types";

export const Cards: Omit<Card, "calculatedStrength">[] = [
  {
    id: 0,
    semanticId: "gwint_card_geralt",
    name: "Geralt of Rivia",
    flavourText:
      "If that's what it takes to save the world, it'd better to let that world die.",
    baseStrength: 15,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
  },
  {
    id: 1,
    semanticId: "gwint_card_ciri",
    name: "Cirilla Fiona Elen Riannon",
    flavourText:
      "Know when fairy tales cease to be tales? When people start believing in them.",
    baseStrength: 15,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
  },
  {
    id: 2,
    semanticId: "gwint_card_triss",
    name: "Triss Merigold",
    flavourText: "I can take care of myself. Trust me.",
    baseStrength: 7,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
  },
  {
    id: 3,
    semanticId: "gwint_card_yennefer",
    name: "Yennefer of Vengerberg",
    flavourText:
      "Magic is Chaos, Art and Science. It is a curse, a blessing and a progression.",
    baseStrength: 7,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC],
  },
  {
    id: 4,
    semanticId: "gwint_card_ballista",
    name: "Ballista",
    flavourText:
      "'Usually we give 'em female names.' 'Like Jenny?' 'More like Bertha.'",
    baseStrength: 6,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
  },
  {
    id: 5,
    semanticId: "gwint_card_blue_stripes",
    name: "Blue Stripes Commando",
    flavourText: "I'd do anything for Temeria. Mostly, though, I kill for her.",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 6,
    semanticId: "gwint_card_blue_stripes",
    name: "Blue Stripes Commando",
    flavourText: "I'd do anything for Temeria. Mostly, though, I kill for her.",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 7,
    semanticId: "gwint_card_blue_stripes",
    name: "Blue Stripes Commando",
    flavourText: "I'd do anything for Temeria. Mostly, though, I kill for her.",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 8,
    semanticId: "gwint_card_catapult",
    name: "Catapult",
    flavourText: "The gods help those who have better catapults.",
    baseStrength: 8,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 9,
    semanticId: "gwint_card_catapult",
    name: "Catapult",
    flavourText: "The gods help those who have better catapults.",
    baseStrength: 8,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 10,
    semanticId: "gwint_card_catapult",
    name: "Catapult",
    flavourText: "The gods help those who have better catapults.",
    baseStrength: 8,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 11,
    semanticId: "gwint_card_crinfrid",
    name: "Crinfrid Reavers Dragon Hunter",
    flavourText: "Haven't had much luck with monsters of late, so we enlisted.",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 12,
    semanticId: "gwint_card_crinfrid",
    name: "Crinfrid Reavers Dragon Hunter",
    flavourText: "Haven't had much luck with monsters of late, so we enlisted.",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 13,
    semanticId: "gwint_card_crinfrid",
    name: "Crinfrid Reavers Dragon Hunter",
    flavourText: "Haven't had much luck with monsters of late, so we enlisted.",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
  },
  {
    id: 14,
    semanticId: "gwint_card_dethmold",
    name: "Dethmold",
    flavourText:
      "I once made a prisoner vomit his own entrails... Ah, good times...",
    baseStrength: 6,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
  },
  {
    id: 15,
    semanticId: "gwint_card_dun_banner_medic",
    name: "Dun Banner Medic",
    flavourText:
      "Stitch red to red, white to white, and everything will be all right.",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.MEDIC],
  },
  {
    id: 16,
    semanticId: "gwint_card_esterad",
    name: "Esterad Thyssen",
    flavourText:
      "Stitch red to red, white to white, and everything will be all right.",
    baseStrength: 10,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.mee],
  },
];
