import { BoardRowType, Card, CardType, Faction, SpecialAbility } from "./types";

export const Cards: Omit<Card, "calculatedStrength">[] = [
  {
    id: 0,
    name: "Arachas",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Ugly - nature's way of saying 'Stay the fuck away.'",
    semanticId: "gwint_card_arachas",
  },
  {
    id: 1,
    name: "Arachas",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Ugly - nature's way of saying 'Stay the fuck away.'",
    semanticId: "gwint_card_arachas",
  },
  {
    id: 2,
    name: "Arachas",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Ugly - nature's way of saying 'Stay the fuck away.'",
    semanticId: "gwint_card_arachas",
  },
  {
    id: 3,
    name: "Arachas Behemoth",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Like a cross between a crab, a spider...and a ploughin' mountain",
    semanticId: "gwint_card_arachas_behemoth",
  },
  {
    id: 4,
    name: "Botchling",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "Admit your mistakes and bury them proper - else they'll come back to haunt you.",
    semanticId: "gwint_card_botchling",
  },
  {
    id: 5,
    name: "Celaeno Harpy",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "Common harpies feed on carrion. Celaeno harpies... they feed on dreams.",
    semanticId: "gwint_card_celaeno_harpy",
  },
  {
    id: 6,
    name: "Cockatrice",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Born of an egg laid by a cockerel... if you believe such peasant drivel.",
    semanticId: "gwint_card_cockatrice",
  },
  {
    id: 7,
    name: "Crone: Brewess",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "We'll cut you up, boy. A fine broth you will make.",
    semanticId: "gwint_card_crone_brewess",
  },
  {
    id: 8,
    name: "Crone: Weavess",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "I sense your pain. I see your fear...",
    semanticId: "gwint_card_crone_weavess",
  },
  {
    id: 9,
    name: "Crone: Whispess",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "I'd be your best - and last.",
    semanticId: "gwint_card_crone_whispess",
  },
  {
    id: 10,
    name: "Draug",
    baseStrength: 10,
    faction: Faction.MONSTERS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "Some men cannot admit defeat. Some keep fighting from beyond the grave.",
    semanticId: "gwint_card_draug",
  },
  {
    id: 11,
    name: "Earth Elemental",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "How to fight an earth elemental? You don't. You run. Fast as you can.",
    semanticId: "gwint_card_earth_elemental",
  },
  {
    id: 12,
    name: "Endrega",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "The nest! Take out the nest, or the bastards'll just keep coming!",
    semanticId: "gwint_card_endrega",
  },
  {
    id: 13,
    name: "Eredin Bréacc Glas: The Treacherous",
    baseStrength: 0,
    faction: Faction.MONSTERS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "I'm enjoying this. You are my toy.",
    semanticId: "gwint_card_eredin_platinium",
  },
  {
    id: 14,
    name: "Eredin: Bringer of Death",
    baseStrength: 0,
    faction: Faction.MONSTERS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "Go on. Show me your spins, pirouettes and feints. I want to watch.",
    semanticId: "gwint_card_eredin_gold",
  },
  {
    id: 15,
    name: "Eredin: Commander of the Red Riders",
    baseStrength: 0,
    faction: Faction.MONSTERS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "Have some dignity. You know how this will end.",
    semanticId: "gwint_card_eredin_bronze",
  },
  {
    id: 16,
    name: "Eredin: Destroyer of Worlds",
    baseStrength: 0,
    faction: Faction.MONSTERS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "It is unavoidable.",
    semanticId: "gwint_card_eredin_silver",
  },
  {
    id: 17,
    name: "Eredin: King of the Wild Hunt",
    baseStrength: 0,
    faction: Faction.MONSTERS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "I've long awaited this...",
    semanticId: "gwint_card_eredin_copper",
  },
  {
    id: 18,
    name: "Fiend",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "A fiend looks a bit like a deer. An enormous, evil deer.",
    semanticId: "gwint_card_fiend",
  },
  {
    id: 19,
    name: "Fire Elemental",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText: "Fire is so delightful.",
    semanticId: "gwint_card_fire_elemental",
  },
  {
    id: 20,
    name: "Fire Elemental",
    baseStrength: 6,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText: "Fire is so delightful.",
    semanticId: "gwint_card_fire_elemental",
  },
  {
    id: 21,
    name: "Foglet",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "Fog creeps on little cat feet. Foglets creep over the bodies of their victims.",
    semanticId: "gwint_card_fogling",
  },
  {
    id: 22,
    name: "Forktail",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "Fork tails... Bah! Fuckers' tails're more like cleavers.",
    semanticId: "gwint_card_forktail",
  },
  {
    id: 23,
    name: "Frightener",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      '"What have I done?" the mage cried out, frightened of his own creation.',
    semanticId: "gwint_card_frightener",
  },
  {
    id: 24,
    name: "Gargoyle",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Ancient sculptors' nightmarish fantasies, brought to life by bored mages.",
    semanticId: "gwint_card_gargoyle",
  },
  {
    id: 25,
    name: "Ghoul",
    baseStrength: 1,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "If ghouls are part of the Circle of Life... then it's a damn vicious circle.",
    semanticId: "gwint_card_ghoul",
  },
  {
    id: 26,
    name: "Ghoul",
    baseStrength: 1,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "If ghouls are part of the Circle of Life... then it's a damn vicious circle.",
    semanticId: "gwint_card_ghoul",
  },
  {
    id: 27,
    name: "Ghoul",
    baseStrength: 1,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "If ghouls are part of the Circle of Life... then it's a damn vicious circle.",
    semanticId: "gwint_card_ghoul",
  },
  {
    id: 28,
    name: "Grave Hag",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Their long tongues're for slurping marrow - and whipping prep.",
    semanticId: "gwint_card_grave_hag",
  },
  {
    id: 29,
    name: "Griffin",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "Griffins like to toy with their prey. Eat 'em alive, piece by piece.",
    semanticId: "gwint_card_griffin",
  },
  {
    id: 30,
    name: "Harpy",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText: "There are many species of harpy, and all are kleptomaniacs.",
    semanticId: "gwint_card_harpy",
  },
  {
    id: 31,
    name: "Ice Giant",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "Fled one time in my life. From the Ice Giant. And I'm not a bit ashamed.",
    semanticId: "gwint_card_ice_giant",
  },
  {
    id: 32,
    name: "Imlerith",
    baseStrength: 10,
    faction: Faction.MONSTERS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "Ladd nahw! Kill them! Litter the earth with their entrails!",
    semanticId: "gwint_card_imlerith",
  },
  {
    id: 33,
    name: "Kayran",
    baseStrength: 8,
    faction: Faction.MONSTERS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [
      SpecialAbility.HERO,
      SpecialAbility.MORALE_BOOST,
      SpecialAbility.AGILE,
    ],
    flavourText:
      "Kill a kayran? Simple. Take your best sword... then sell it and hire a witcher.",
    semanticId: "gwint_card_kayran",
  },
  {
    id: 34,
    name: "Leshen",
    baseStrength: 10,
    faction: Faction.MONSTERS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "We never hunt in these woods. Not even if it means the whole village starves.",
    semanticId: "gwint_card_leshen",
  },
  {
    id: 35,
    name: "Nekker",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Damn things are almost cute, if you ignore the whole vicious killer aspect.",
    semanticId: "gwint_card_nekker",
  },
  {
    id: 36,
    name: "Nekker",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Damn things are almost cute, if you ignore the whole vicious killer aspect.",
    semanticId: "gwint_card_nekker",
  },
  {
    id: 37,
    name: "Nekker",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Damn things are almost cute, if you ignore the whole vicious killer aspect.",
    semanticId: "gwint_card_nekker",
  },
  {
    id: 38,
    name: "Plague Maiden",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "The sick rave about a boil-pocked woman surrounded by herds of rabid rats...",
    semanticId: "gwint_card_plague_maiden",
  },
  {
    id: 39,
    name: "Toad",
    baseStrength: 7,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.SCORCH],
    flavourText: "Big. Bad. Ugly. Squats in the sewers.",
    semanticId: "gwint_card_toad",
  },
  {
    id: 40,
    name: "Vampire: Bruxa",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "A vile, bloodthirsty, man-eating hag. Kind of like my mother-in-law.",
    semanticId: "gwint_card_bruxa",
  },
  {
    id: 41,
    name: "Vampire: Bruxa",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "A vile, bloodthirsty, man-eating hag. Kind of like my mother-in-law.",
    semanticId: "gwint_card_bruxa",
  },
  {
    id: 42,
    name: "Vampire: Ekimmara",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Who would think overgrown bats would have a taste for gaudy jewelry?",
    semanticId: "gwint_card_ekkima",
  },
  {
    id: 43,
    name: "Vampire: Fleder",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Higher vampires embrace their victims. Fleders rip them to shreds.",
    semanticId: "gwint_card_fleder",
  },
  {
    id: 44,
    name: "Vampire: Garkain",
    baseStrength: 4,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Blood-drinkers and corpse-eaters so foul their very ugliness paralyses foes.",
    semanticId: "gwint_card_garkain",
  },
  {
    id: 45,
    name: "Vampire: Katakan",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Drinking the blood of the Continent since the Conjunction.",
    semanticId: "gwint_card_katakan",
  },
  {
    id: 46,
    name: "Werewolf",
    baseStrength: 5,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "Wolves aren't as bad as they say. Werewolves, though - they're worse.",
    semanticId: "gwint_card_werewolf",
  },
  {
    id: 47,
    name: "Wyvern",
    baseStrength: 2,
    faction: Faction.MONSTERS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Imagine a cross between a winged snake and a nightmare. Wyverns are worse.",
    semanticId: "gwint_card_wyvern",
  },
  {
    id: 48,
    name: "Assire var Anahid",
    baseStrength: 6,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Nilfgaardian mages do have a choice: servile submission, or the gallows.",
    semanticId: "gwint_card_assire",
  },
  {
    id: 49,
    name: "Black Infantry Archer",
    baseStrength: 10,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText: "I aim for the knee. Always.",
    semanticId: "gwint_card_black_archer",
  },
  {
    id: 50,
    name: "Black Infantry Archer",
    baseStrength: 10,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText: "I aim for the knee. Always.",
    semanticId: "gwint_card_black_archer",
  },
  {
    id: 51,
    name: "Cahir Mawr Dyffryn aep Ceallach",
    baseStrength: 6,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "His eyes flashed under his winged helmet. Fire gleamed from his sword's blade.",
    semanticId: "gwint_card_cahir",
  },
  {
    id: 52,
    name: "Cynthia",
    baseStrength: 4,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText: "Cynthia's talents can be deadly. She needs a tight leash.",
    semanticId: "gwint_card_cynthia",
  },
  {
    id: 53,
    name: "Emhyr var Emreis: Emperor of Nilfgaard",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "Your motives do not interest me. Only results.",
    semanticId: "gwint_card_emhyr_bronze",
  },
  {
    id: 54,
    name: "Emhyr var Emreis: Emperor of Nilfgaard",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "Your motives do not interest me. Only results.",
    semanticId: "gwint_card_emhyr_bronze",
  },
  {
    id: 55,
    name: "Emhyr var Emreis: His Imperial Majesty",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "The skies wept when my Pavetta died. They will not weep for me.",
    semanticId: "gwint_card_emhyr_copper",
  },
  {
    id: 56,
    name: "Emhyr var Emreis: Invader of the North",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "Emperors command multitudes, yet cannot control two things: their time and their hearts.",
    semanticId: "gwint_card_emhyr_platinium",
  },
  {
    id: 57,
    name: "Emhyr var Emreis: The Relentless",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "They do not call me the Patient. Take care they do not call you the Headless.",
    semanticId: "gwint_card_emhyr_gold",
  },
  {
    id: 58,
    name: "Emhyr var Emreis: The White Flame",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "A sword is but one of many tools at a ruler's disposal.",
    semanticId: "gwint_card_emhyr_silver",
  },
  {
    id: 59,
    name: "Etolian Auxiliary Archers",
    baseStrength: 1,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "Double or nothing, aim for his cock.",
    semanticId: "gwint_card_archer_support",
  },
  {
    id: 60,
    name: "Etolian Auxiliary Archers",
    baseStrength: 1,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "Double or nothing, aim for his cock.",
    semanticId: "gwint_card_archer_support",
  },
  {
    id: 61,
    name: "Fringilla Vigo",
    baseStrength: 6,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Magic is the highest good. It transcends all borders and divisions.",
    semanticId: "gwint_card_fringilla",
  },
  {
    id: 62,
    name: "Heavy Zerrikanian Fire Scorpion",
    baseStrength: 10,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "Not the best for taking cities, but great for razing them to the ground.",
    semanticId: "gwint_card_heavy_zerri",
  },
  {
    id: 63,
    name: "Impera Brigade Guard",
    baseStrength: 3,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The Impera Brigade never surrenders. Ever.",
    semanticId: "gwint_card_impera_brigade",
  },
  {
    id: 64,
    name: "Impera Brigade Guard",
    baseStrength: 3,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The Impera Brigade never surrenders. Ever.",
    semanticId: "gwint_card_impera_brigade",
  },
  {
    id: 65,
    name: "Impera Brigade Guard",
    baseStrength: 3,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The Impera Brigade never surrenders. Ever.",
    semanticId: "gwint_card_impera_brigade",
  },
  {
    id: 66,
    name: "Impera Brigade Guard",
    baseStrength: 3,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The Impera Brigade never surrenders. Ever.",
    semanticId: "gwint_card_impera_brigade",
  },
  {
    id: 67,
    name: "Letho of Gulet",
    baseStrength: 10,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "Witchers never die in their beds.",
    semanticId: "gwint_card_letho",
  },
  {
    id: 68,
    name: "Menno Coehoorn",
    baseStrength: 10,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO, SpecialAbility.MEDIC],
    flavourText:
      "I'll take an attentive reconnaissance unit over a fine cavalry brigade any day.",
    semanticId: "gwint_card_menno",
  },
  {
    id: 69,
    name: "Morteisen",
    baseStrength: 3,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "No Nordling pikemen or dwarven spearbearers can hope to best trained cavalry.",
    semanticId: "gwint_card_morteisen",
  },
  {
    id: 70,
    name: "Morvran Voorhis",
    baseStrength: 10,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "Summer sun reflecting in the quiet waters of the Alba - that's Nilfgaard to me.",
    semanticId: "gwint_card_moorvran",
  },
  {
    id: 71,
    name: "Nausicaa Cavalry Rider",
    baseStrength: 2,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The Emperor will teach the North discipline.",
    semanticId: "gwint_card_nausicaa",
  },
  {
    id: 72,
    name: "Nausicaa Cavalry Rider",
    baseStrength: 2,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The Emperor will teach the North discipline.",
    semanticId: "gwint_card_nausicaa",
  },
  {
    id: 73,
    name: "Nausicaa Cavalry Rider",
    baseStrength: 2,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The Emperor will teach the North discipline.",
    semanticId: "gwint_card_nausicaa",
  },
  {
    id: 74,
    name: "Puttkammer",
    baseStrength: 3,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Learned a lot at Braibant Military Academy. How to scrub potatoes, for instance.",
    semanticId: "gwint_card_puttkammer",
  },
  {
    id: 75,
    name: "Rainfarn",
    baseStrength: 4,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "You'll die as painfully as that pathetic traitor Windhalm did.",
    semanticId: "gwint_card_rainfarn",
  },
  {
    id: 76,
    name: "Renuald aep Matsen",
    baseStrength: 5,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "They say the Impera fear nothing. Untrue. Renuald scares them shitless.",
    semanticId: "gwint_card_renuald",
  },
  {
    id: 77,
    name: "Rotten Mangonel",
    baseStrength: 3,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText: "The rotten smell brings back childhood memories",
    semanticId: "gwint_card_rotten",
  },
  {
    id: 78,
    name: "Shilard Fitz-Oesterlen",
    baseStrength: 7,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SPY],
    flavourText:
      "Warfare is mere sound and fury - diplomacy is what truly shapes history.",
    semanticId: "gwint_card_shilard",
  },
  {
    id: 79,
    name: "Siege Engineer",
    baseStrength: 6,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText: "Wielded correctly, a protractor can be a deadly weapon.",
    semanticId: "gwint_card_combat_engineer",
  },
  {
    id: 80,
    name: "Siege Engineer",
    baseStrength: 6,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText: "Wielded correctly, a protractor can be a deadly weapon.",
    semanticId: "gwint_card_combat_engineer",
  },
  {
    id: 81,
    name: "Siege Technician",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "I never miss twice.",
    semanticId: "gwint_card_siege_support",
  },
  {
    id: 82,
    name: "Siege Technician",
    baseStrength: 0,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "I never miss twice.",
    semanticId: "gwint_card_siege_support",
  },
  {
    id: 83,
    name: "Stefan Skellen",
    baseStrength: 9,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SPY],
    flavourText:
      "My mark scars the face of our future empress. That is my proudest achievement.",
    semanticId: "gwint_card_stefan",
  },
  {
    id: 84,
    name: "Sweers",
    baseStrength: 2,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "And hands off the girl! Whatever we may be, we're not savages.",
    semanticId: "gwint_card_sweers",
  },
  {
    id: 85,
    name: "Tibor Eggebracht",
    baseStrength: 10,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "Albaaaa! Forward!! Alba! Long live the Emperor!",
    semanticId: "gwint_card_tibor",
  },
  {
    id: 86,
    name: "Vanhemar",
    baseStrength: 4,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText: "For a fire mage, he's not very... flamboyant.",
    semanticId: "gwint_card_vanhemar",
  },
  {
    id: 87,
    name: "Vattier de Rideaux",
    baseStrength: 4,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SPY],
    flavourText:
      "There's never been a problem a well-planned assassination couldn't solve.",
    semanticId: "gwint_card_vattier",
  },
  {
    id: 88,
    name: "Vreemde",
    baseStrength: 2,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "Discipline is the Empire's deadliest weapon.",
    semanticId: "gwint_card_vreemde",
  },
  {
    id: 89,
    name: "Young Emissary",
    baseStrength: 5,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText:
      "If I acquit myself well, perhaps next they'll post me somewhere civilized.",
    semanticId: "gwint_card_young_emissary",
  },
  {
    id: 90,
    name: "Young Emissary",
    baseStrength: 5,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText:
      "If I acquit myself well, perhaps next they'll post me somewhere civilized.",
    semanticId: "gwint_card_young_emissary",
  },
  {
    id: 91,
    name: "Zerrikanian Fire Scorpion",
    baseStrength: 5,
    faction: Faction.NILFGAARDIAN_EMPIRE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "The Zerrikania Desert used to be a lush garden. Then these came along.",
    semanticId: "gwint_card_zerri",
  },
  {
    id: 92,
    name: "Ballista",
    baseStrength: 6,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "'Usually we give 'em female names.' 'Like Jenny?' 'More like Bertha.'",
    semanticId: "gwint_card_ballista",
  },
  {
    id: 93,
    name: "Blue Stripes Commando",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "I'd do anything for Temeria. Mostly, though, I kill for her.",
    semanticId: "gwint_card_blue_stripes",
  },
  {
    id: 94,
    name: "Blue Stripes Commando",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "I'd do anything for Temeria. Mostly, though, I kill for her.",
    semanticId: "gwint_card_blue_stripes",
  },
  {
    id: 95,
    name: "Blue Stripes Commando",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "I'd do anything for Temeria. Mostly, though, I kill for her.",
    semanticId: "gwint_card_blue_stripes",
  },
  {
    id: 96,
    name: "Catapult",
    baseStrength: 8,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The gods help those who have better catapults.",
    semanticId: "gwint_card_catapult",
  },
  {
    id: 97,
    name: "Catapult",
    baseStrength: 8,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The gods help those who have better catapults.",
    semanticId: "gwint_card_catapult",
  },
  {
    id: 98,
    name: "Catapult",
    baseStrength: 8,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "The gods help those who have better catapults.",
    semanticId: "gwint_card_catapult",
  },
  {
    id: 99,
    name: "Crinfrid Reavers Dragon Hunter",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "Haven't had much luck with monsters of late, so we enlisted.",
    semanticId: "gwint_card_crinfrid",
  },
  {
    id: 100,
    name: "Crinfrid Reavers Dragon Hunter",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "Haven't had much luck with monsters of late, so we enlisted.",
    semanticId: "gwint_card_crinfrid",
  },
  {
    id: 101,
    name: "Crinfrid Reavers Dragon Hunter",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "Haven't had much luck with monsters of late, so we enlisted.",
    semanticId: "gwint_card_crinfrid",
  },
  {
    id: 102,
    name: "Dethmold",
    baseStrength: 6,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "I once made a prisoner vomit his own entrails... Ah, good times...",
    semanticId: "gwint_card_dethmold",
  },
  {
    id: 103,
    name: "Dun Banner Medic",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText:
      "Stitch red to red, white to white, and everything will be all right.",
    semanticId:
      'gwint_card_dun_banner_medic<sup id="cite_ref-1" class="reference"><a href="#cite_note-1">[1]</a></sup>',
  },
  {
    id: 104,
    name: "Esterad Thyssen",
    baseStrength: 10,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "Like all Thyssen men, he was tall, powerfully built and criminally handsome.",
    semanticId: "gwint_card_esterad",
  },
  {
    id: 105,
    name: "Foltest: King of Temeria",
    baseStrength: 0,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "It is natural and beautiful that a man should love his sister.",
    semanticId: "gwint_card_foltest_copper",
  },
  {
    id: 106,
    name: "Foltest: Lord Commander of the North",
    baseStrength: 0,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "Sod advisors and their schemes. I place my trust in my solders' blades.",
    semanticId: "gwint_card_foltest_bronze",
  },
  {
    id: 107,
    name: "Foltest: Son of Medell",
    baseStrength: 0,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "Dammit, I rule this land and I refuse to creep around its corners.",
    semanticId: "gwint_card_foltest_platinium",
  },
  {
    id: 108,
    name: "Foltest: The Siegemaster",
    baseStrength: 0,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "A well-aimed ballista razes not just the enemy's walls, but his morale as well.",
    semanticId: "gwint_card_foltest_silver",
  },
  {
    id: 109,
    name: "Foltest: The Steel-Forged",
    baseStrength: 0,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "A beautiful day for battle.",
    semanticId: "gwint_card_foltest_gold",
  },
  {
    id: 110,
    name: "John Natalis",
    baseStrength: 10,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "That square should bear the names of my soldiers, of the dead. Not mine.",
    semanticId: "gwint_card_natalis",
  },
  {
    id: 111,
    name: "Kaedweni Siege Expert",
    baseStrength: 1,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.MORALE_BOOST],
    flavourText:
      "'You gotta recalibrate the arm by five degrees.' 'Do what by the what now?'",
    semanticId: "gwint_card_kaedwen_siege",
  },
  {
    id: 112,
    name: "Keira Metz",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "If I'm to die today, I wish to look smashing for the occasion.",
    semanticId: "gwint_card_keira",
  },
  {
    id: 113,
    name: "Philippa Eilhart",
    baseStrength: 10,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "Soon the power of kings will wither, and the Lodge shall seize its rightful place.",
    semanticId: "gwint_card_philippa",
  },
  {
    id: 114,
    name: "Poor Fucking Infantry",
    baseStrength: 1,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "I's a war veteran! ... spare me a crown?",
    semanticId: "gwint_card_poor_infantry2",
  },
  {
    id: 115,
    name: "Poor Fucking Infantry",
    baseStrength: 1,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "I's a war veteran! ... spare me a crown?",
    semanticId: "gwint_card_poor_infantry2",
  },
  {
    id: 116,
    name: "Poor Fucking Infantry",
    baseStrength: 1,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "I's a war veteran! ... spare me a crown?",
    semanticId: "gwint_card_poor_infantry2",
  },
  {
    id: 117,
    name: "Prince Stennis",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SPY],
    flavourText:
      "He ploughin' wears golden armor. Golden. 'Course he's an arsehole.",
    semanticId: "gwint_card_stennis",
  },
  {
    id: 118,
    name: "Redanian Foot Soldier",
    baseStrength: 1,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I've bled for Redania! I've killed for Redania... Dammit, I've even raped for Redania!",
    semanticId: "gwint_card_redania",
  },
  {
    id: 119,
    name: "Sabrina Glevissig",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText: "The Daughter of the Kaedweni Wilderness.",
    semanticId: "gwint_card_sabrina",
  },
  {
    id: 120,
    name: "Sheldon Skaggs",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "I was there, on the front lines! Right where the fightin' was the thickest!",
    semanticId: "gwint_card_sheldon",
  },
  {
    id: 121,
    name: "Siege Tower",
    baseStrength: 6,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "I love the clamor of siege towers in the morning. Sounds like victory.",
    semanticId: "gwint_card_siege_tower",
  },
  {
    id: 122,
    name: "Siegfried of Denesle",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "We're on the same side, witcher. You'll realize this one day.",
    semanticId: "gwint_card_siegfried",
  },
  {
    id: 123,
    name: "Sigismund Dijkstra",
    baseStrength: 4,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SPY],
    flavourText: "Gwent's like politics, just more honest.",
    semanticId: "gwint_card_dijkstra",
  },
  {
    id: 124,
    name: "Síle de Tansarville",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "The Lodge lacks humility. Our lust for power may yet be our undoing.",
    semanticId: "gwint_name_sile",
  },
  {
    id: 125,
    name: "Thaler",
    baseStrength: 1,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.SPY],
    flavourText:
      "Fuck off! We aren't all ploughin' philanderers. Some of us have depth...",
    semanticId: "gwint_card_thaler",
  },
  {
    id: 126,
    name: "Trebuchet",
    baseStrength: 6,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "Castle won't batter itself down, now will it? Get them trebuchets rollin'!",
    semanticId: "gwint_card_trebuchet",
  },
  {
    id: 127,
    name: "Vernon Roche",
    baseStrength: 10,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "A patriot... and a real son of a bitch.",
    semanticId: "gwint_card_vernon",
  },
  {
    id: 128,
    name: "Ves",
    baseStrength: 5,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "Better to live one day as a king than a whole life as a beggar.",
    semanticId: "gwint_card_ves",
  },
  {
    id: 129,
    name: "Yarpen Zigrin",
    baseStrength: 2,
    faction: Faction.NORTHERN_REALMS,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "The world belongs to whoever's best at crackin' skulls and impregnatin' lasses.",
    semanticId: "gwint_card_yarpen",
  },
  {
    id: 130,
    name: "Barclay Els",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "Our mead smells like piss, do it? Easy to fix - I'll break your fuckin' nose!",
    semanticId: "gwint_card_barclay",
  },
  {
    id: 131,
    name: "Barclay Els",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "Our mead smells like piss, do it? Easy to fix - I'll break your fuckin' nose!",
    semanticId: "gwint_card_barclay",
  },
  {
    id: 132,
    name: "Barclay Els",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "Our mead smells like piss, do it? Easy to fix - I'll break your fuckin' nose!",
    semanticId: "gwint_card_barclay",
  },
  {
    id: 133,
    name: "Ciaran aep Easnillien",
    baseStrength: 3,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText: "The path to freedom is paved in blood, not ink.",
    semanticId: "gwint_card_ciaran",
  },
  {
    id: 134,
    name: "Dennis Cranmer",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I know how to carry out orders, so you can shove your advice up your coal chute.",
    semanticId: "gwint_card_dennis",
  },
  {
    id: 135,
    name: "Dol Blathanna Archer",
    baseStrength: 4,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Take another step, dh'oine. You'd look better with an arrow between your eyes.",
    semanticId: "gwint_card_dol_archer",
  },
  {
    id: 136,
    name: "Dol Blathanna Archer",
    baseStrength: 4,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Take another step, dh'oine. You'd look better with an arrow between your eyes.",
    semanticId: "gwint_card_dol_archer",
  },
  {
    id: 137,
    name: "Dol Blathanna Archer",
    baseStrength: 4,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Take another step, dh'oine. You'd look better with an arrow between your eyes.",
    semanticId: "gwint_card_dol_archer",
  },
  {
    id: 138,
    name: "Dol Blathanna Scout",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "They track like hounds, run like deer and kill like cold-hearted bastards.",
    semanticId: "gwint_card_dol_infantry",
  },
  {
    id: 139,
    name: "Dol Blathanna Scout",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "They track like hounds, run like deer and kill like cold-hearted bastards.",
    semanticId: "gwint_card_dol_infantry",
  },
  {
    id: 140,
    name: "Dol Blathanna Scout",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "They track like hounds, run like deer and kill like cold-hearted bastards.",
    semanticId: "gwint_card_dol_infantry",
  },
  {
    id: 141,
    name: "Dol Blathanna Scout",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "They track like hounds, run like deer and kill like cold-hearted bastards.",
    semanticId: "gwint_card_dol_infantry",
  },
  {
    id: 142,
    name: "Dwarven Skirmisher",
    baseStrength: 3,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Worked a pickaxe all me life. Battleaxe won't be any trouble.",
    semanticId: "gwint_card_dol_dwarf",
  },
  {
    id: 143,
    name: "Dwarven Skirmisher",
    baseStrength: 3,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Worked a pickaxe all me life. Battleaxe won't be any trouble.",
    semanticId: "gwint_card_dol_dwarf",
  },
  {
    id: 144,
    name: "Dwarven Skirmisher",
    baseStrength: 3,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "Worked a pickaxe all me life. Battleaxe won't be any trouble.",
    semanticId: "gwint_card_dol_dwarf",
  },
  {
    id: 145,
    name: "Eithné",
    baseStrength: 10,
    faction: Faction.SCOIATAEL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "The dryad queen has eyes of molten silver, and a heart of cold-forged steel.",
    semanticId: "gwint_card_eithne",
  },
  {
    id: 146,
    name: "Elven Skirmisher",
    baseStrength: 2,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "No matter what you may have heard, elves don't take human scalps. Too much lice.",
    semanticId: "gwint_card_elf_skirmisher",
  },
  {
    id: 147,
    name: "Elven Skirmisher",
    baseStrength: 2,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "No matter what you may have heard, elves don't take human scalps. Too much lice.",
    semanticId: "gwint_card_elf_skirmisher",
  },
  {
    id: 148,
    name: "Elven Skirmisher",
    baseStrength: 2,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "No matter what you may have heard, elves don't take human scalps. Too much lice.",
    semanticId: "gwint_card_elf_skirmisher",
  },
  {
    id: 149,
    name: "Filavandrel aen Fidhail",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "Though we are now few and scattered, our hearts burn brighter than ever.",
    semanticId: "gwint_card_filavandrel",
  },
  {
    id: 150,
    name: "Francesca Findabair: Daisy of the Valley",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "The Elder Races have forgotten more than humans can ever hope to know.",
    semanticId: "gwint_card_francesca_bronze",
  },
  {
    id: 151,
    name: "Francesca Findabair: Hope of the Aen Seidhe",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "Daede sian caente, Aen Seidhe en'allane ael coeden...",
    semanticId: "gwint_card_francesca_platinium",
  },
  {
    id: 152,
    name: "Francesca Findabair: Pureblood Elf",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "Ash shall fertilize the soil. By spring, the valley shall bloom once more.",
    semanticId: "gwint_card_francesca_copper",
  },
  {
    id: 153,
    name: "Francesca Findabair: Queen of Dol Blathanna",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "To live in peace, we first must kill. This is human oppression's cruel finale.",
    semanticId: "gwint_card_francesca_gold",
  },
  {
    id: 154,
    name: "Francesca Findabair: The Beautiful",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "Do not let my beauty distract your aim.",
    semanticId: "gwint_card_francesca_silver",
  },
  {
    id: 155,
    name: "Havekar Healer",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "Sure, I'll patch you up. Gonna cost you, though.",
    semanticId: "gwint_card_havekar_nurse",
  },
  {
    id: 156,
    name: "Havekar Healer",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "Sure, I'll patch you up. Gonna cost you, though.",
    semanticId: "gwint_card_havekar_nurse",
  },
  {
    id: 157,
    name: "Havekar Healer",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "Sure, I'll patch you up. Gonna cost you, though.",
    semanticId: "gwint_card_havekar_nurse",
  },
  {
    id: 158,
    name: "Havekar Healer",
    baseStrength: 0,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "Sure, I'll patch you up. Gonna cost you, though.",
    semanticId: "gwint_card_havekar_nurse",
  },
  {
    id: 159,
    name: "Havekar Smuggler",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "I fight for whoever's paying the best. Or whoever's easiest to rob.",
    semanticId: "gwint_card_havekar_support",
  },
  {
    id: 160,
    name: "Havekar Smuggler",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "I fight for whoever's paying the best. Or whoever's easiest to rob.",
    semanticId: "gwint_card_havekar_support",
  },
  {
    id: 161,
    name: "Havekar Smuggler",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "I fight for whoever's paying the best. Or whoever's easiest to rob.",
    semanticId: "gwint_card_havekar_support",
  },
  {
    id: 162,
    name: "Havekar Smuggler",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "I fight for whoever's paying the best. Or whoever's easiest to rob.",
    semanticId: "gwint_card_havekar_support",
  },
  {
    id: 163,
    name: "Ida Emean aep Sivney",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "I am a Sage. My power lies in possessing knowledge. Not sharing it.",
    semanticId: "gwint_card_ida",
  },
  {
    id: 164,
    name: "Iorveth",
    baseStrength: 10,
    faction: Faction.SCOIATAEL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "King or beggar, what's the difference? One dh'oine less.",
    semanticId: "gwint_card_iorveth",
  },
  {
    id: 165,
    name: "Isengrim Faoiltiarna",
    baseStrength: 10,
    faction: Faction.SCOIATAEL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MORALE_BOOST, SpecialAbility.HERO],
    flavourText:
      "It dawns on them once they notice my scar: a realization of imminent death.",
    semanticId: "gwint_card_isengrim",
  },
  {
    id: 166,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 167,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 168,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 169,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 170,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 171,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 172,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 173,
    name: "Mahakaman Defender",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "I'm telling ye, we're born fer battle - we slash straight at their knees!",
    semanticId: "gwint_card_mahakam",
  },
  {
    id: 174,
    name: "Milva",
    baseStrength: 10,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MORALE_BOOST],
    flavourText:
      "With each arrow I loose, I think of my da. He'd be proud. I think.",
    semanticId: "gwint_card_milva",
  },
  {
    id: 175,
    name: "Riordain",
    baseStrength: 1,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Stare into their eyes, feast on their terror. Then go in for the kill.",
    semanticId: "gwint_card_riordain",
  },
  {
    id: 176,
    name: "Saesenthessis",
    baseStrength: 10,
    faction: Faction.SCOIATAEL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "Beautiful, pure, fierce - the prefect icon for a rebellion.",
    semanticId: "gwint_card_saskia",
  },
  {
    id: 177,
    name: "Schirrú",
    baseStrength: 8,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.SCORCH],
    flavourText: "Time to look death in the face.",
    semanticId: "gwint_card_schirru",
  },
  {
    id: 178,
    name: "Toruviel",
    baseStrength: 2,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "I'd gladly kill you from up close, stare in your eyes... But you reek, human.",
    semanticId: "gwint_card_toruviel",
  },
  {
    id: 179,
    name: "Vrihedd Brigade Recruit",
    baseStrength: 4,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "Hatred burns brighter than any fire, and cuts deeper than any blade.",
    semanticId: "gwint_card_vrihedd_cadet",
  },
  {
    id: 180,
    name: "Vrihedd Brigade Veteran",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText: "'Vrihedd? What's that mean?' 'Trouble.'",
    semanticId: "gwint_card_vrihedd_brigade",
  },
  {
    id: 181,
    name: "Vrihedd Brigade Veteran",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText: "'Vrihedd? What's that mean?' 'Trouble.'",
    semanticId: "gwint_card_vrihedd_brigade",
  },
  {
    id: 182,
    name: "Vrihedd Brigade Veteran",
    baseStrength: 5,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText: "'Vrihedd? What's that mean?' 'Trouble.'",
    semanticId: "gwint_card_vrihedd_brigade",
  },
  {
    id: 183,
    name: "Yaevinn",
    baseStrength: 6,
    faction: Faction.SCOIATAEL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE],
    flavourText:
      "We are the drops of rain that together make a ferocious storm.",
    semanticId: "gwint_card_yaevinn",
  },
  {
    id: 184,
    name: "Berserker",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.BERSERK],
    flavourText: "Kill, crush, cleave!",
    semanticId: "gwint_card_berserker",
  },
  {
    id: 185,
    name: "Birna Bran",
    baseStrength: 2,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MEDIC],
    flavourText: "Skellige must have a strong king. No matter what it takes.",
    semanticId: "gwint_card_birna_bran",
  },
  {
    id: 186,
    name: "Blueboy Lugos",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "I'm damn near ready to puke from boredom.",
    semanticId: "gwint_card_blueboy_lugos",
  },
  {
    id: 187,
    name: "Cerys",
    baseStrength: 10,
    faction: Faction.SKELLIGE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO, SpecialAbility.MUSTER],
    flavourText:
      "They call me Sparrowhawk, know why? Because I eat rats like you for breakfast.",
    semanticId: "gwint_card_cerys",
  },
  {
    id: 188,
    name: "Clan Brokvar Archer",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "So ye can hit a movin' target at two hundred paces. Me, too. In a storm.",
    semanticId: "gwint_card_clan_brokvar_archer",
  },
  {
    id: 189,
    name: "Clan Brokvar Archer",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "So ye can hit a movin' target at two hundred paces. Me, too. In a storm.",
    semanticId: "gwint_card_clan_brokvar_archer",
  },
  {
    id: 190,
    name: "Clan Brokvar Archer",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [],
    flavourText:
      "So ye can hit a movin' target at two hundred paces. Me, too. In a storm.",
    semanticId: "gwint_card_clan_brokvar_archer",
  },
  {
    id: 191,
    name: "Clan Dimun Pirate",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.SCORCH],
    flavourText:
      "Can see the fear in their eyes. Fear o' me... fear o' Clan Dimun!",
    semanticId: "gwint_card_clan_dimun_pirate",
  },
  {
    id: 192,
    name: "Clan Drummond Shield Maiden",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "They'll shatter on our shields like waves on a rocky shore.",
    semanticId: "gwint_card_clan_drummond_shieldmaiden",
  },
  {
    id: 193,
    name: "Clan Drummond Shield Maiden",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "They'll shatter on our shields like waves on a rocky shore.",
    semanticId: "gwint_card_clan_drummond_shieldmaiden",
  },
  {
    id: 194,
    name: "Clan Drummond Shield Maiden",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "They'll shatter on our shields like waves on a rocky shore.",
    semanticId: "gwint_card_clan_drummond_shieldmaiden",
  },
  {
    id: 195,
    name: "Clan Heymaey Skald",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "The deeds of Clan Heymaey will go down in history.",
    semanticId: "gwint_card_clan_heymaey_skald",
  },
  {
    id: 196,
    name: "Clan Tordarroch Armorsmith",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "Ye're in for a poundin'.",
    semanticId: "gwint_card_clan_tordarroch_armorsmith",
  },
  {
    id: 197,
    name: "Clan an Craite Warrior",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText:
      "I'll bring the an Craites such glory, bards'll go hoarse singin' me praises!",
    semanticId: "gwint_card_clan_an_craite_warrior",
  },
  {
    id: 198,
    name: "Crach an Craite",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText:
      "A king's gotta be wise. A king's gotta command respect. A king's gotta have stones.",
    semanticId: "gwint_card_king_bran_copper",
  },
  {
    id: 199,
    name: "Donar an Hindar",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "I've gathered all the jarls together. Now make your case.",
    semanticId: "gwint_card_donar_an_hindar",
  },
  {
    id: 200,
    name: "Draig Bon-Dhu",
    baseStrength: 2,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.HORN],
    flavourText: "Hear ye now the tale of the heroic deeds of Clan an Craite.",
    semanticId: "gwint_card_draig",
  },
  {
    id: 201,
    name: "Ermion",
    baseStrength: 8,
    faction: Faction.SKELLIGE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO, SpecialAbility.MARDROEME],
    flavourText: "Only the ignorant dismiss the importance of myths.",
    semanticId: "gwint_card_ermion",
  },
  {
    id: 202,
    name: "Hemdall",
    baseStrength: 11,
    faction: Faction.SKELLIGE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText:
      "When the time of the White Frost comes, Hemdall will sound the call for battle.",
    semanticId: "",
    isHiddenCard: true,
  },
  {
    id: 203,
    name: "Hjalmar",
    baseStrength: 10,
    faction: Faction.SKELLIGE,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "Instead of mournin' the fallen, let's drink to their memory!",
    semanticId: "gwint_card_hjalmar",
  },
  {
    id: 204,
    name: "Holger Blackhand",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [],
    flavourText:
      "Now let's drink to Emperor of Nilfgaard - may his prick forever stay limp!",
    semanticId: "gwint_card_holger_blackhand",
  },
  {
    id: 205,
    name: "Kambi",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SUMMON_AVENGER],
    flavourText:
      "When the time comes, the cockerel Kambi shall crow and awaken Hemdall.",
    semanticId: "gwint_card_cock",
  },
  {
    id: 206,
    name: "King Bran",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "No one can replace Bran. Though they're sure to try.",
    semanticId: "gwint_card_king_bran_bronze",
  },
  {
    id: 207,
    name: "King Bran",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.LEADER,
    allowedRows: [],
    specialAbilities: [],
    flavourText: "No one can replace Bran. Though they're sure to try.",
    semanticId: "gwint_card_king_bran_bronze",
  },
  {
    id: 208,
    name: "Light Longship",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Escape them? In the waters of Skellige? Good luck.",
    semanticId: "gwint_card_light_drakkar",
  },
  {
    id: 209,
    name: "Light Longship",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Escape them? In the waters of Skellige? Good luck.",
    semanticId: "gwint_card_light_drakkar",
  },
  {
    id: 210,
    name: "Light Longship",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Escape them? In the waters of Skellige? Good luck.",
    semanticId: "gwint_card_light_drakkar",
  },
  {
    id: 211,
    name: "Madman Lugos",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "WAAAAAAAAAAGH!!!!",
    semanticId: "gwint_card_madman_lugos",
  },
  {
    id: 212,
    name: "Mardroeme",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.MARDROEME],
    flavourText: "Eat enough of them, and the world will never be the same...",
    semanticId: "gwint_card_mushroom",
  },
  {
    id: 213,
    name: "Mardroeme",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.MARDROEME],
    flavourText: "Eat enough of them, and the world will never be the same...",
    semanticId: "gwint_card_mushroom",
  },
  {
    id: 214,
    name: "Mardroeme",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.MARDROEME],
    flavourText: "Eat enough of them, and the world will never be the same...",
    semanticId: "gwint_card_mushroom",
  },
  {
    id: 215,
    name: "Olaf",
    baseStrength: 12,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.AGILE, SpecialAbility.MORALE_BOOST],
    flavourText:
      "Many've tried to defeat Olaf. But won't hear about it from them - they're dead.",
    semanticId: "gwint_card_olaf",
  },
  {
    id: 216,
    name: "Skellige Storm",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "This ain't no normal storm. This here's the wrath of the gods.",
    semanticId: "gwint_card_skellige_storm",
  },
  {
    id: 217,
    name: "Skellige Storm",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "This ain't no normal storm. This here's the wrath of the gods.",
    semanticId: "gwint_card_skellige_storm",
  },
  {
    id: 218,
    name: "Skellige Storm",
    baseStrength: 0,
    faction: Faction.SKELLIGE,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "This ain't no normal storm. This here's the wrath of the gods.",
    semanticId: "gwint_card_skellige_storm",
  },
  {
    id: 219,
    name: "Svanrige",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "The emperor also thought him an accidental king. At first.",
    semanticId: "gwint_card_svanrige",
  },
  {
    id: 220,
    name: "Transformed Vildkaarl",
    baseStrength: 14,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.MORALE_BOOST],
    flavourText: "Saw them fight once in my life... and once was enough.",
    semanticId: "",
    isHiddenCard: true,
  },
  {
    id: 221,
    name: "Transformed Young Vildkaarl",
    baseStrength: 8,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText: "Rooaaaar!",
    semanticId: "",
    isHiddenCard: true,
  },
  {
    id: 222,
    name: "Udalryk",
    baseStrength: 4,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "Haaaargh! After me, if ye've the bollocks!",
    semanticId: "gwint_card_udalryk",
  },
  {
    id: 223,
    name: "War Longship",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText:
      "They say Hemdall's heart swells whenever the longships sail out on a raid.",
    semanticId: "gwint_card_war_drakkar",
  },
  {
    id: 224,
    name: "War Longship",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText:
      "They say Hemdall's heart swells whenever the longships sail out on a raid.",
    semanticId: "gwint_card_war_drakkar",
  },
  {
    id: 225,
    name: "War Longship",
    baseStrength: 6,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.TIGHT_BOND],
    flavourText:
      "They say Hemdall's heart swells whenever the longships sail out on a raid.",
    semanticId: "gwint_card_war_drakkar",
  },
  {
    id: 226,
    name: "Young Berserker",
    baseStrength: 2,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.BERSERK],
    flavourText: "Want some?",
    semanticId: "gwint_card_young_berserker",
  },
  {
    id: 227,
    name: "Young Berserker",
    baseStrength: 2,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.BERSERK],
    flavourText: "Want some?",
    semanticId: "gwint_card_young_berserker",
  },
  {
    id: 228,
    name: "Young Berserker",
    baseStrength: 2,
    faction: Faction.SKELLIGE,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.BERSERK],
    flavourText: "Want some?",
    semanticId: "gwint_card_young_berserker",
  },
  {
    id: 229,
    name: "Biting Frost",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "Best part about frost - bodies of the fallen don't rot so quickly.",
    semanticId: "gwint_card_frost",
  },
  {
    id: 230,
    name: "Biting Frost",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "Best part about frost - bodies of the fallen don't rot so quickly.",
    semanticId: "gwint_card_frost",
  },
  {
    id: 231,
    name: "Biting Frost",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "Best part about frost - bodies of the fallen don't rot so quickly.",
    semanticId: "gwint_card_frost",
  },
  {
    id: 232,
    name: "Bovine Defense Force",
    baseStrength: 8,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: "Grrrrr!",
    semanticId: "",
    isHiddenCard: true,
  },
  {
    id: 233,
    name: "Cirilla Fiona Elen Riannon",
    baseStrength: 15,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO, SpecialAbility.MUSTER],
    flavourText:
      "Know when fairy tales cease to be tales? When people start believing in them.",
    semanticId: "gwint_card_ciri",
  },
  {
    id: 234,
    name: "Clear Weather",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.CLEAR_WEATHER],
    flavourText:
      "The sun's shinin', Dromle! The sun's shinin'! Maybe there's hope left after all...",
    semanticId: "gwint_card_clear_sky",
  },
  {
    id: 235,
    name: "Clear Weather",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.CLEAR_WEATHER],
    flavourText:
      "The sun's shinin', Dromle! The sun's shinin'! Maybe there's hope left after all...",
    semanticId: "gwint_card_clear_sky",
  },
  {
    id: 236,
    name: "Clear Weather",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.CLEAR_WEATHER],
    flavourText:
      "The sun's shinin', Dromle! The sun's shinin'! Maybe there's hope left after all...",
    semanticId: "gwint_card_clear_sky",
  },
  {
    id: 237,
    name: "Commander's Horn",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.HORN],
    flavourText: "Plus one to morale, minus three to hearing.",
    semanticId: "gwint_card_horn",
  },
  {
    id: 238,
    name: "Commander's Horn",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.HORN],
    flavourText: "Plus one to morale, minus three to hearing.",
    semanticId: "gwint_card_horn",
  },
  {
    id: 239,
    name: "Commander's Horn",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.HORN],
    flavourText: "Plus one to morale, minus three to hearing.",
    semanticId: "gwint_card_horn",
  },
  {
    id: 240,
    name: "Commander's Horn",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.HORN],
    flavourText: "Plus one to morale, minus three to hearing.",
    semanticId: "gwint_card_horn",
  },
  {
    id: 241,
    name: "Commander's Horn",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.HORN],
    flavourText: "Plus one to morale, minus three to hearing.",
    semanticId: "gwint_card_horn",
  },
  {
    id: 242,
    name: "Cow",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.SUMMON_AVENGER],
    flavourText: "Mooo!",
    semanticId: "gwint_card_cow",
  },
  {
    id: 243,
    name: "Dandelion",
    baseStrength: 2,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HORN],
    flavourText:
      "Dandelion, you're a cynic, a lecher, a whoremonger, a liar - and my best friend.",
    semanticId: "gwint_card_dandelion",
  },
  {
    id: 244,
    name: "Decoy",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.DECOY],
    flavourText:
      "When you run out of peasants, decoys also make decent arrow fodder.",
    semanticId: "gwint_card_dummy",
  },
  {
    id: 245,
    name: "Decoy",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.DECOY],
    flavourText:
      "When you run out of peasants, decoys also make decent arrow fodder.",
    semanticId: "gwint_card_dummy",
  },
  {
    id: 246,
    name: "Decoy",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.DECOY],
    flavourText:
      "When you run out of peasants, decoys also make decent arrow fodder.",
    semanticId: "gwint_card_dummy",
  },
  {
    id: 247,
    name: "Emiel Regis Rohellec Terzieff",
    baseStrength: 5,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "Men, the polite ones, at least, would call me a monster. A blood-drinking freak.",
    semanticId: "gwint_card_emiel",
  },
  {
    id: 248,
    name: "Gaunter O'Dimm",
    baseStrength: 2,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.SIEGE],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText:
      "He always grants exactly what you wish for. That's the problem.",
    semanticId: "gwint_card_mrmirror",
  },
  {
    id: 249,
    name: "Gaunter O'Dimm: Darkness",
    baseStrength: 4,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Fear not the shadows, but the light.",
    semanticId: "gwint_card_mrmirror_foglet",
  },
  {
    id: 250,
    name: "Gaunter O'Dimm: Darkness",
    baseStrength: 4,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Fear not the shadows, but the light.",
    semanticId: "gwint_card_mrmirror_foglet",
  },
  {
    id: 251,
    name: "Gaunter O'Dimm: Darkness",
    baseStrength: 4,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MUSTER],
    flavourText: "Fear not the shadows, but the light.",
    semanticId: "gwint_card_mrmirror_foglet",
  },
  {
    id: 252,
    name: "Geralt of Rivia",
    baseStrength: 15,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO, SpecialAbility.MUSTER],
    flavourText:
      "If that's what it takes to save the world, it'd better to let that world die.",
    semanticId: "gwint_card_geralt",
  },
  {
    id: 253,
    name: "Impenetrable Fog",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText: "A good commander's dream... a bad one's horror.",
    semanticId: "gwint_card_fog",
  },
  {
    id: 254,
    name: "Impenetrable Fog",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText: "A good commander's dream... a bad one's horror.",
    semanticId: "gwint_card_fog",
  },
  {
    id: 255,
    name: "Impenetrable Fog",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText: "A good commander's dream... a bad one's horror.",
    semanticId: "gwint_card_fog",
  },
  {
    id: 256,
    name: "Mysterious Elf",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SPY, SpecialAbility.HERO],
    flavourText: "You humans have... unusual tastes.",
    semanticId: "gwint_card_avallach",
  },
  {
    id: 257,
    name: "Olgierd von Everec",
    baseStrength: 6,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE, BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MORALE_BOOST, SpecialAbility.AGILE],
    flavourText: "At least you now know I don't easily lose my head",
    semanticId: "gwint_card_olgierd",
  },
  {
    id: 258,
    name: "Roach",
    baseStrength: 3,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText: '"Come on, Roach! Faster!"',
    semanticId: "gwint_card_roach",
  },
  {
    id: 259,
    name: "Scorch",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.SCORCH],
    flavourText:
      "Pillars of flame turn the mightiest to ash. All others tremble in shock and awe.",
    semanticId: "gwint_card_scorch",
  },
  {
    id: 260,
    name: "Scorch",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.SCORCH],
    flavourText:
      "Pillars of flame turn the mightiest to ash. All others tremble in shock and awe.",
    semanticId: "gwint_card_scorch",
  },
  {
    id: 261,
    name: "Scorch",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.SPECIAL,
    allowedRows: [],
    specialAbilities: [SpecialAbility.SCORCH],
    flavourText:
      "Pillars of flame turn the mightiest to ash. All others tremble in shock and awe.",
    semanticId: "gwint_card_scorch",
  },
  {
    id: 262,
    name: "Skellige Storm",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "This ain't no normal storm. This here's the wrath of the gods.",
    semanticId: "gwint_card_skellige_storm",
  },
  {
    id: 263,
    name: "Skellige Storm",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "This ain't no normal storm. This here's the wrath of the gods.",
    semanticId: "gwint_card_skellige_storm",
  },
  {
    id: 264,
    name: "Skellige Storm",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText:
      "This ain't no normal storm. This here's the wrath of the gods.",
    semanticId: "gwint_card_skellige_storm",
  },
  {
    id: 265,
    name: "Torrential Rain",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText: "Even the rain in this land smells like piss.",
    semanticId: "gwint_card_rain",
  },
  {
    id: 266,
    name: "Torrential Rain",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText: "Even the rain in this land smells like piss.",
    semanticId: "gwint_card_rain",
  },
  {
    id: 267,
    name: "Torrential Rain",
    baseStrength: 0,
    faction: Faction.NEUTRAL,
    type: CardType.WEATHER,
    allowedRows: [],
    specialAbilities: [SpecialAbility.WEATHER],
    flavourText: "Even the rain in this land smells like piss.",
    semanticId: "gwint_card_rain",
  },
  {
    id: 268,
    name: "Triss Merigold",
    baseStrength: 7,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.HERO],
    flavourText: "I can take care of myself. Trust me.",
    semanticId: "gwint_card_triss",
  },
  {
    id: 269,
    name: "Vesemir",
    baseStrength: 6,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "If you're to be hanged, ask for water. Anything can happen before they fetch it.",
    semanticId: "gwint_card_vesemir",
  },
  {
    id: 270,
    name: "Villentretenmerth",
    baseStrength: 7,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [SpecialAbility.SCORCH],
    flavourText:
      "Also calls himself Borkh Three Jackdaws... he's not the best at names.",
    semanticId: "gwint_card_villen",
  },
  {
    id: 271,
    name: "Yennefer of Vengerberg",
    baseStrength: 7,
    faction: Faction.NEUTRAL,
    type: CardType.HERO,
    allowedRows: [BoardRowType.RANGED],
    specialAbilities: [SpecialAbility.MEDIC, SpecialAbility.HERO],
    flavourText:
      "Magic is Chaos, Art and Science. It is a curse, a blessing and a progression.",
    semanticId: "gwint_card_yennefer",
  },
  {
    id: 272,
    name: "Zoltan Chivay",
    baseStrength: 5,
    faction: Faction.NEUTRAL,
    type: CardType.UNIT,
    allowedRows: [BoardRowType.MELEE],
    specialAbilities: [],
    flavourText:
      "Life without old mates and booze is like a woman without a rump.",
    semanticId: "gwint_card_zoltan",
  },
];
