export const NUMBER_OF_PLAYERS = 2;
export const NUMBER_OF_STARTING_CARDS_IN_HAND = 10;
export const MINIMUM_NUMBER_OF_UNIT_CARDS_IN_DECK = 22;
export const MAXIMUM_NUMBER_OF_SPECIAL_CARDS_IN_DECK = 10;
